# Generated by Django 3.0 on 2019-12-04 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='is_store',
            field=models.IntegerField(choices=[(1, '现货'), (0, '非现货')], default=0, verbose_name='是否现货'),
        ),
    ]
