# Generated by Django 3.0 on 2019-12-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products_app', '0003_auto_20191204_1404'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='is_on',
            field=models.IntegerField(choices=[(1, '现货'), (0, '非现货')], default=1, verbose_name='是否上架'),
        ),
        migrations.AlterField(
            model_name='products',
            name='product_uprice',
            field=models.DecimalField(decimal_places=2, max_digits=7, null=True),
        ),
    ]
