# Generated by Django 3.0.1 on 2019-12-26 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermodel',
            name='remark_name',
            field=models.CharField(help_text='用户备注', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='usermodel',
            name='tel_phone',
            field=models.CharField(help_text='电话号码', max_length=200, null=True),
        ),
    ]
